### ISSUE TITLE
Error when call Props in mdx

### ISSUE THREAD

**Issue by ltsfran** [wilsson/papyrum#18]
When I try to call Props of @papyrum/ui-docs, it doesn't recognize the declared props in component.

![ButtonComponent](https://user-images.githubusercontent.com/38477522/65470860-8f92bb80-de32-11e9-844a-f74fff9fcb47.png)
![ButtonMdx](https://user-images.githubusercontent.com/38477522/65470944-d54f8400-de32-11e9-9042-6ac8244ca10f.png)
![Error2](https://user-images.githubusercontent.com/38477522/65470997-12b41180-de33-11e9-8cb4-48357539bc3e.png)

It seems that the **watch** expects to make a **Ctrl + S** in the mdx as well. If I save both files for more than in the MDX I have already saved, if it shows.

![Correct](https://user-images.githubusercontent.com/38477522/65471133-ab4a9180-de33-11e9-8a0c-e9c8a5870e5a.png)

**Comment by wilsson** [comment]
resolved in the new redesign
