### ISSUE TITLE
Add template config

### ISSUE THREAD

**Issue by juanpablocs** [wilsson/papyrum#4]
Currently the html of each external project uses a base html that is inside the core papyurm

The idea is to create one more option in the papyrum config `papyrumrc.js` a key that points to an own base HTML template.

```js
export default {
  menu: [
    'Introduction',
    'Colors',
    'Fonts',
    'Components'
  ],
  template: 'index.html' // new config
};
```

**Comment by wilsson** [comment]
Proceed with the development

**Comment by wilsson** [comment]
#6 task completed, closed
